### ISSUE TITLE
Shared "Memorable Quotes" List

### ISSUE THREAD

**Issue by v3xx3d** [PingPesto/octobot#25]
The current quote thing in Slack is cool but it would be awesome to have one shared among everyone.

**Comment by chuckbutler** [comment]
It appears that the "Pinned Messages" accomplish this functionality - https://slack.zendesk.com/hc/en-us/articles/201925108-Understanding-channels-private-groups-direct-messages

**Comment by v3xx3d** [comment]
Looks that way. Thanks.
